version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    expose:
      - "9000"  # Meng-expose port 9000 untuk komunikasi dengan Nginx
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www  # Mount folder aplikasi Laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount konfigurasi Nginx
    ports:
      - "8000:80"  # Arahkan port 8000 di host ke port 80 di container Nginx
    depends_on:
      - app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
